### ISSUE TITLE
Making cgSpan mine closed graphs as defined in the CloseGraph paper

### ISSUE THREAD

**Issue by Nojgaard** [NaazS03/cgSpan#2]
Hey all,

I would be super interested in using this tool to a project I'm working on. 

I was wondering how difficult it would be to change cgspan to mine closed graphs as defined in the CloseGraph paper (i.e. disregard the number of isomorphisms when determining if a graph is closed or not). I guess I would have to change the way the _early_termination and check_equivalent_occurence work, by disregarding finding the isomorphisms in those functions. However, I am unsure if the algorithm would still be correct in this case. I tried to read the associated papers, however I am not sure I quite grasp the details to the point I would understand the consequences of such a change.

Sincerely,
Nikolai

**Comment by shaulz** [comment]
Hello Nikolai,

Can you please provide the exact definition of closed graph you want to
implement?
Please provide an example of the current result and result you want to
achieve.

Thanks,
    Shaul

**Comment by Nojgaard** [comment]
Hey Shaul, 

Thanks for the reply! From the cgSpan paper [here](http://www.philippe-fournier-viger.com/spmf/cgspan_closed.pdf) on Figure 1 I am only interested in the mining of g'_1 and not g'_2 (as g'_1 is a supergraph of g'_2 and they share the same support). The formal definition of such closed graphs are given in the paragraph just above Figure 1:
CS = {g|g ∈ FS and ∄g′ ∈FS such that g ⊂ g′ and support(g) = support(g′)}

Sincerely,
Nikolai

**Comment by shaulz** [comment]
Hi Nikolai,

One thing you can easily do is to replace _has_equivalent_extended_occurrence_projections call in cgspan.py with _has_equivalent_extended_occurrence_graphs. 

This will not solve your example. I can not see an easy way to modify the code so it will output closed subgraphs according to ClosedGraph definition.
Even if we modify _early_termination and check_equivalent_occurence to consider support and not projections, we cannot guarantee that check_equivalent_occurence will be invoked, since the hash key may not be found.
For example consider two database graphs:
A-B-C-D-B-C
A-B-C-E-B-C
By ClosedGraph definition only A-B-C is a closed subgraph. We need  check_equivalent_occurence of A-B-C to be called with
B-C, but that will not happen because B-C hashkey is different (contains 4 edges) from that of A-B-C (contains only two edges). 

Thanks,
Shaul

**Comment by Nojgaard** [comment]
Hey Shaul,

Thanks for the answers, they have been of great help! I will try and see if I can incorporate these changes into a fork. :)

Sincerely,
Nikolai
